{% set name = "lightning-bolts" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightning-bolts-{{ version }}.tar.gz
  sha256: 6071cda7721087890ba01523d6580fe72b03b842766fd5018a8eb9caa99fe75c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - packaging
    - python >={{ python_min }}
    - numpy
    - pytorch-lightning >=1.7.0, <2.0.0
    - torchmetrics >=0.10.0, <0.12.0
    - lightning-utilities >0.3.1
    - tensorboard >=2.9.1, <2.14.0
    - torchvision >=0.10.0

test:
  imports:
    - pl_bolts
    - pl_bolts.callbacks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Lightning-AI/lightning-bolts
  summary: PyTorch Lightning Bolts is a community contribution for ML researchers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - Tobias-Fischer
